export const NOT_EMPTY_MESSAGE = "Não é permitido enviar valores vazios."
export const NAME_MESSAGE = "Por favor, informe o nome completo."
export const EMAIL_MESSAGE = "Por favor, informe um endereço de e-mail válido."
export const EMAIL_EXISTS_MESSAGE = "Endereço de e-mail já está cadastrado."
export const STRONG_PASSWORD_MESSAGE = "Por favor, digite uma senha forte."
